/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteHabitacion.Vistas;

import clienteHabitacion.ClienteMedico;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servidorAlertas.dto.UsuarioDTO;
import servidorAlertas.sop_rmi.GestionPacienteInt;

/**
 *
 * @author usuario
 */
public class RegistarPaciente extends javax.swing.JFrame {

    public static GestionPacienteInt objRemoto;
    public static ClienteMedico cm;

    /**
     * Creates new form prueba
     */
    public RegistarPaciente(GestionPacienteInt objRemoto, ClienteMedico cm) {
        this.objRemoto = objRemoto;
        this.cm = cm;
        initComponents();
    }

    public RegistarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_prueba = new javax.swing.JButton();
        lb_id = new javax.swing.JLabel();
        lb_tipoId = new javax.swing.JLabel();
        lb_nombres = new javax.swing.JLabel();
        lb_apellidos = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        txf_id = new javax.swing.JTextField();
        txf_tipoId = new javax.swing.JTextField();
        txf_nombres = new javax.swing.JTextField();
        txf_apellidos = new javax.swing.JTextField();
        txf_direccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_prueba.setText("prueba");
        btn_prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pruebaActionPerformed(evt);
            }
        });

        lb_id.setText("ID");

        lb_tipoId.setText("Tipo ID");

        lb_nombres.setText("Nombres");

        lb_apellidos.setText("Apellidos");

        lb_direccion.setText("Dirección");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_tipoId)
                            .addComponent(lb_id)
                            .addComponent(lb_nombres)
                            .addComponent(lb_apellidos)
                            .addComponent(lb_direccion))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_id, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(txf_tipoId)
                            .addComponent(txf_nombres)
                            .addComponent(txf_apellidos)
                            .addComponent(txf_direccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_prueba)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_id)
                    .addComponent(txf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipoId)
                    .addComponent(txf_tipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombres)
                    .addComponent(txf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_apellidos)
                    .addComponent(txf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_direccion)
                    .addComponent(txf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_prueba)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pruebaActionPerformed
        try {
            // TODO add your handling code here:
            int id = Integer.parseInt(txf_id.getText());
            String tipoId = txf_tipoId.getText();
            String nombres = txf_nombres.getText();
            String apellidos = txf_apellidos.getText();
            String direccion = txf_apellidos.getText();

            JOptionPane.showMessageDialog(null, "valor coincidencia: "+ cm.existeId(id, objRemoto));
            if (cm.existeId(id, objRemoto)) {
                JOptionPane.showMessageDialog(null, "El id ya existe");
            } else {
                UsuarioDTO paciente = new UsuarioDTO(id, tipoId, nombres, apellidos, direccion);
                objRemoto.registrarPaciente(paciente);
                ArrayList<UsuarioDTO> array = objRemoto.listarPacientes();
                JOptionPane.showMessageDialog(null, "tam Array: " + objRemoto.listarPacientes().size());
                for (int i = 0; i < array.size(); i++) {
                    JOptionPane.showMessageDialog(null, "id: " + array.get(i).getId());
                    JOptionPane.showMessageDialog(null, "tipoid: " + array.get(i).getTipo_id());
                    JOptionPane.showMessageDialog(null, "nombre " + array.get(i).getNombres());
                    JOptionPane.showMessageDialog(null, "apellido: " + array.get(i).getApellidos());
                    JOptionPane.showMessageDialog(null, "direccion: " + array.get(i).getDireccion());
                }
                JOptionPane.showMessageDialog(null, "Paciente registrado con éxito ");
                this.setVisible(false);
                MenuMedico menu = new MenuMedico(objRemoto, cm);
                menu.setVisible(true);
            }

        } catch (RemoteException ex) {
            Logger.getLogger(RegistarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_pruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prueba;
    private javax.swing.JLabel lb_apellidos;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_tipoId;
    private javax.swing.JTextField txf_apellidos;
    private javax.swing.JTextField txf_direccion;
    private javax.swing.JTextField txf_id;
    private javax.swing.JTextField txf_nombres;
    private javax.swing.JTextField txf_tipoId;
    // End of variables declaration//GEN-END:variables
}
